# Generated by Django 4.1.7 on 2023-07-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bbag_delete_bag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bbag',
            new_name='Bag',
        ),
    ]
