# Generated by Django 4.1.7 on 2023-07-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_bbag_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='age',
            field=models.IntegerField(default='1'),
        ),
    ]
