# Generated by Django 4.1.7 on 2023-07-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bag_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='pic',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
